# Global config — AUTO-GENERATED by scripts/generate-r2-config.sh from
# infra/r2-config.yaml. Do not edit manually.
# Reference these in generated HCL via: global.r2_bucket, global.r2_region, etc.

globals {
  # Cloudflare R2 state backend
  r2_bucket = "autolab-opentofu-state"
  r2_region = "auto"
}
