#!/bin/bash
# Env file format helpers (source from other scripts).
# Owns the two-file split: /etc/default/proxmox-network.env (main) and
# /etc/default/network-uplink-failover (derived).
#
# Provides: env_file_set, write_failover_env, write_env, load_existing_env,
#           prompt_into, prompt_secret_into

# Append or update one key=value line with shell-safe quoting.
env_file_set() {
  local file="$1" key="$2" value="$3"
  local tmp
  tmp="$(mktemp)"
  if [[ -f "${file}" ]]; then
    grep -v "^${key}=" "${file}" > "${tmp}" || true
  fi
  printf '%s=%q\n' "${key}" "${value}" >> "${tmp}"
  mv "${tmp}" "${file}"
  chmod 600 "${file}" 2>/dev/null || true
}

# Write the failover env file (derived from main env vars).
# systemd EnvironmentFile + bash source — values must not contain spaces.
write_failover_env() {
  local file="${1:-/etc/default/network-uplink-failover}"
  local v
  for v in "${ETH_USB:-}" "${WIFI}" "${GW}" "${VMBR:-vmbr0}" "${VMBR_IP}"; do
    [[ "${v}" != *" "* ]] || {
      echo "ERROR: failover env values must not contain spaces: ${v}" >&2
      return 1
    }
  done
  cat > "${file}" << EOF
ETH_USB=${ETH_USB:-}
WIFI=${WIFI}
GW=${GW}
VMBR=${VMBR:-vmbr0}
VMBR_IP=${VMBR_IP}
EOF
  chmod 600 "${file}"
}

# Write all key=value pairs to an env file (used by configure script).
# Usage: write_env "/path/to/file" KEY1 "val1" KEY2 "val2" ...
write_env() {
  local out="$1"
  shift
  {
    echo "# Generated by configure-proxmox-network-env.sh on $(date -Iseconds)"
    while [[ $# -gt 0 ]]; do
      local k="$1"
      local v="$2"
      shift 2
      printf '%s=%q\n' "${k}" "${v}"
    done
  } > "${out}"
  chmod 600 "${out}"
}

# Source an existing env file if it exists, warning on parse errors.
load_existing_env() {
  local file="${1:-/etc/default/proxmox-network.env}"
  if [[ -f "${file}" ]]; then
    set +e
    # shellcheck source=/dev/null
    source "${file}" 2>/dev/null
    local rc=$?
    set -e
    if [[ $rc -ne 0 ]]; then
      echo "WARNING: Existing ${file} is not valid shell; will overwrite if you continue." >&2
    fi
  fi
}

# Interactive prompt: read a value from /dev/tty with a default.
# Sets the named variable via printf -v.
prompt_into() {
  local __var="$1"
  local label="$2"
  local default="$3"
  local input=""
  read -r -p "${label} [${default}]: " input </dev/tty
  if [[ -n "${input}" ]]; then
    printf -v "${__var}" '%s' "${input}"
  else
    printf -v "${__var}" '%s' "${default}"
  fi
}

# Interactive prompt for a secret (hidden input) with sanitization.
# Sets the named variable via printf -v.
prompt_secret_into() {
  local __var="$1"
  local label="$2"
  local default="$3"
  local raw="" clean=""
  while true; do
    read -r -s -p "${label} (hidden, type password then Enter): " raw </dev/tty
    echo ""
    if [[ -z "${raw}" ]]; then
      if [[ -n "${default}" ]]; then
        raw="${default}"
        echo "  (using password already in ${OUT})" >&2
      else
        echo "  Password cannot be empty — type it and press Enter once." >&2
        continue
      fi
    fi
    clean="$(sanitize_secret "${raw}")"
    if [[ -z "${clean}" ]]; then
      echo "  Password was only whitespace/newlines — try again." >&2
      continue
    fi
    if [[ "${raw}" != "${clean}" ]]; then
      echo "WARNING: Removed newline(s) from ${label} (paste with extra line breaks)." >&2
    fi
    printf -v "${__var}" '%s' "${clean}"
    return
  done
}