#!/usr/bin/env bats
# Tests for lib/env-config.sh

bats_require_minimum_version 1.5.0

load test_helper

# ── env_file_set ────────────────────────────────────────────────────────────

@test "env_file_set writes a new key=value pair" {
  source "${SCRIPT_DIR}/lib/env-config.sh"
  local tmpfile="${TMPDIR}/test.env"

  env_file_set "${tmpfile}" "TEST_KEY" "hello world"

  # File should exist and contain the key
  [[ -f "${tmpfile}" ]]
  grep -q "^TEST_KEY=" "${tmpfile}"

  # Sourcing the file should set the variable with the original value
  # shellcheck disable=SC1090
  source "${tmpfile}"
  [[ "${TEST_KEY}" == "hello world" ]]
}

@test "env_file_set replaces an existing key" {
  source "${SCRIPT_DIR}/lib/env-config.sh"
  local tmpfile="${TMPDIR}/test.env"

  # Write initial value
  env_file_set "${tmpfile}" "TEST_KEY" "old value"
  # shellcheck disable=SC1090
  source "${tmpfile}"
  [[ "${TEST_KEY}" == "old value" ]]

  # Update the value
  env_file_set "${tmpfile}" "TEST_KEY" "new value"
  # shellcheck disable=SC1090
  source "${tmpfile}"
  [[ "${TEST_KEY}" == "new value" ]]

  # Verify only one occurrence of TEST_KEY exists
  [[ "$(grep -c "^TEST_KEY=" "${tmpfile}")" -eq 1 ]]
}

# ── write_failover_env ──────────────────────────────────────────────────────

@test "write_failover_env writes all 5 keys" {
  source "${SCRIPT_DIR}/lib/env-config.sh"
  local tmpfile="${TMPDIR}/failover.env"

  export ETH_USB="enx00e04c123456"
  export WIFI="wlp2s0"
  export GW="10.0.0.1"
  export VMBR="vmbr0"
  export VMBR_IP="10.0.0.5/24"

  run write_failover_env "${tmpfile}"
  [ "$status" -eq 0 ]

  grep -q "^ETH_USB=" "${tmpfile}"
  grep -q "^WIFI=" "${tmpfile}"
  grep -q "^GW=" "${tmpfile}"
  grep -q "^VMBR=" "${tmpfile}"
  grep -q "^VMBR_IP=" "${tmpfile}"
}

@test "write_failover_env rejects values containing spaces" {
  source "${SCRIPT_DIR}/lib/env-config.sh"
  local tmpfile="${TMPDIR}/failover.env"

  export ETH_USB="enx00e04c123456"
  export WIFI="wlp2s0"
  export GW="10.0.0.1"
  export VMBR="vmbr0"
  export VMBR_IP="10.0.0 5/24"   # contains a space → should fail

  run write_failover_env "${tmpfile}"
  [ "$status" -ne 0 ]
  [[ "$output" == *"ERROR"* ]]
}

# ── write_env ───────────────────────────────────────────────────────────────

@test "write_env writes key=value pairs with header and chmod 600" {
  source "${SCRIPT_DIR}/lib/env-config.sh"
  local tmpfile="${TMPDIR}/write.env"

  write_env "${tmpfile}" "KEY1" "val1" "KEY2" "val with spaces"

  # Header line present
  head -1 "${tmpfile}" | grep -q "^# Generated by configure-proxmox-network-env.sh"

  # Keys present
  grep -q "^KEY1=" "${tmpfile}"
  grep -q "^KEY2=" "${tmpfile}"

  # File is valid shell and values can be sourced correctly
  # shellcheck disable=SC1090
  source "${tmpfile}"
  [[ "${KEY1}" == "val1" ]]
  [[ "${KEY2}" == "val with spaces" ]]

  # Check chmod 600 (portable: verify owner-only read/write via ls -l)
  [[ "$(ls -l "${tmpfile}" | cut -d' ' -f1)" =~ ^-rw------- ]]
}

# ── load_existing_env ───────────────────────────────────────────────────────

@test "load_existing_env sources a valid env file" {
  source "${SCRIPT_DIR}/lib/env-config.sh"
  local tmpfile="${TMPDIR}/valid.env"

  printf '%s=%q\n' "TEST_VAR" "hello" > "${tmpfile}"

  load_existing_env "${tmpfile}"
  [[ "${TEST_VAR}" == "hello" ]]
}

@test "load_existing_env warns on invalid env file without aborting" {
  source "${SCRIPT_DIR}/lib/env-config.sh"
  local tmpfile="${TMPDIR}/invalid.env"

  echo "THIS IS NOT VALID SHELL @@@" > "${tmpfile}"

  # Capture both stdout and stderr
  run bash -c "source '${SCRIPT_DIR}/lib/env-config.sh' && load_existing_env '${tmpfile}'" 2>&1
  [ "$status" -eq 0 ]
  [[ "$output" == *"WARNING"* ]]
}
