#!/bin/bash
# Interactive helper: create /etc/default/proxmox-network.env
# Run on the Proxmox host as root before setup-proxmox-network.sh
set -euo pipefail

OUT="${OUT:-/etc/default/proxmox-network.env}"
WIFI_EXTRA_LIST="/etc/default/proxmox-wifi-extra.list"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/network-env-validate.sh
source "${SCRIPT_DIR}/lib/network-env-validate.sh"

detect_iface() {
  ip -br link 2>/dev/null | awk -v p="$1" '$1 ~ p { print $1; exit }'
}

detect_gw() {
  ip route show default 2>/dev/null | awk '{print $3; exit}'
}

detect_vmbr_ip() {
  ip -4 addr show dev vmbr0 2>/dev/null | awk '/inet / { print $2; exit }'
}

detect_wifi_ip() {
  local wifi="$1"
  ip -4 addr show dev "${wifi}" 2>/dev/null | awk '/inet / { print $2; exit }'
}

# Pick a sensible default management IP on the same subnet as the gateway.
suggest_vmbr_ip() {
  local gw="$1"
  local wifi="$2"
  local ip

  ip="$(detect_vmbr_ip)"
  if [[ -n "${ip}" ]]; then
    echo "${ip}"
    return
  fi

  ip="$(detect_wifi_ip "${wifi}")"
  if [[ -n "${ip}" ]]; then
    echo "${ip}"
    return
  fi

  if [[ "${gw}" =~ ^([0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+$ ]]; then
    echo "${BASH_REMATCH[1]}.130/24"
    return
  fi

  echo "192.168.1.100/24"
}

load_existing_env() {
  if [[ -f "${OUT}" ]]; then
    set +e
    # shellcheck source=/dev/null
    source "${OUT}" 2>/dev/null
    local rc=$?
    set -e
    if [[ $rc -ne 0 ]]; then
      echo "WARNING: Existing ${OUT} is not valid shell; will overwrite if you continue." >&2
    fi
  fi
}

# Interactive reads MUST use /dev/tty — never VAR="$(read …)" (read would not see the keyboard).
prompt_into() {
  local __var="$1"
  local label="$2"
  local default="$3"
  local input=""
  read -r -p "${label} [${default}]: " input </dev/tty
  if [[ -n "${input}" ]]; then
    printf -v "${__var}" '%s' "${input}"
  else
    printf -v "${__var}" '%s' "${default}"
  fi
}

prompt_secret_into() {
  local __var="$1"
  local label="$2"
  local default="$3"
  local raw="" clean=""
  while true; do
    read -r -s -p "${label} (hidden, type password then Enter): " raw </dev/tty
    echo ""
    if [[ -z "${raw}" ]]; then
      if [[ -n "${default}" ]]; then
        raw="${default}"
        echo "  (using password already in ${OUT})" >&2
      else
        echo "  Password cannot be empty — type it and press Enter once." >&2
        continue
      fi
    fi
    clean="$(sanitize_secret "${raw}")"
    if [[ -z "${clean}" ]]; then
      echo "  Password was only whitespace/newlines — try again." >&2
      continue
    fi
    if [[ "${raw}" != "${clean}" ]]; then
      echo "WARNING: Removed newline(s) from ${label} (paste with extra line breaks)." >&2
    fi
    printf -v "${__var}" '%s' "${clean}"
    return
  done
}

write_env() {
  local out="$1"
  shift
  {
    echo "# Generated by configure-proxmox-network-env.sh on $(date -Iseconds)"
    while [[ $# -gt 0 ]]; do
      local k="$1"
      local v="$2"
      shift 2
      printf '%s=%q\n' "${k}" "${v}"
    done
  } > "${out}"
  chmod 600 "${out}"
}

ETH_USB="$(detect_iface '^enx')"
WIFI="$(detect_iface '^wlp')"

[[ -n "${WIFI}" ]] || { echo "No Wi-Fi interface (wlp*) found." >&2; exit 1; }

load_existing_env
GW="${GW:-$(detect_gw)}"
VMBR_SUGGEST="$(suggest_vmbr_ip "${GW}" "${WIFI}")"

DEF_HOME_SSID="${WPA_HOME_SSID:-your_home_ssid}"
DEF_HOME_PSK="${WPA_HOME_PSK:-}"
if secret_has_newline "${DEF_HOME_PSK}"; then
  echo "WARNING: Existing WPA_HOME_PSK had newline(s); will sanitize if you keep it." >&2
  DEF_HOME_PSK="$(sanitize_secret "${DEF_HOME_PSK}")" || true
fi
if secret_has_newline "${WPA_HOTSPOT_PSK:-}"; then
  echo "WARNING: Existing WPA_HOTSPOT_PSK had newline(s); will sanitize if you keep it." >&2
  WPA_HOTSPOT_PSK="$(sanitize_secret "${WPA_HOTSPOT_PSK}")" || true
fi
DEF_COUNTRY="${WPA_COUNTRY:-US}"
DEF_GW="${GW:-192.168.1.1}"
DEF_VMBR="${VMBR_IP:-${VMBR_SUGGEST}}"

echo "=== Proxmox network config helper ==="
echo "Writes: ${OUT}"
echo ""
echo "Detected:"
echo "  ETH_USB=${ETH_USB:-<none — plug USB Ethernet or leave empty>}"
echo "  WIFI=${WIFI}"
echo "  GW=${GW:-<unknown>}"
echo "  VMBR_IP (suggested)=${VMBR_SUGGEST}"
echo ""

CLEAR_EXTRA_WIFI=0
if [[ -f "${OUT}" ]]; then
  read -r -p "Overwrite ${OUT}? [y/N]: " ow </dev/tty
  [[ "${ow,,}" == "y" ]] || { echo "Aborted."; exit 0; }
  if [[ -f "${WIFI_EXTRA_LIST}" && -s "${WIFI_EXTRA_LIST}" ]]; then
    read -r -p "Also clear extra Wi-Fi list (${WIFI_EXTRA_LIST})? [y/N]: " clr </dev/tty
    [[ "${clr,,}" == "y" ]] && CLEAR_EXTRA_WIFI=1
  fi
fi

echo ""
echo "--- Wi-Fi (SSID/password — only values we cannot guess) ---"
prompt_into WPA_COUNTRY "Country code (WPA)" "${DEF_COUNTRY}"
prompt_into WPA_HOME_SSID "Home Wi-Fi SSID" "${DEF_HOME_SSID}"
echo ""
prompt_secret_into WPA_HOME_PSK "Home Wi-Fi password" "${DEF_HOME_PSK}"
prompt_into WPA_HOME_PRIORITY "Home priority (higher = preferred)" "${WPA_HOME_PRIORITY:-10}"

echo ""
read -r -p "Add phone hotspot? [y/N]: " add_hotspot </dev/tty
WPA_HOTSPOT_SSID="${WPA_HOTSPOT_SSID:-}"
WPA_HOTSPOT_PSK="${WPA_HOTSPOT_PSK:-}"
WPA_HOTSPOT_PRIORITY="${WPA_HOTSPOT_PRIORITY:-5}"
if [[ "${add_hotspot,,}" == "y" ]]; then
  prompt_into WPA_HOTSPOT_SSID "Hotspot SSID" "${WPA_HOTSPOT_SSID}"
  echo ""
  prompt_secret_into WPA_HOTSPOT_PSK "Hotspot password" "${WPA_HOTSPOT_PSK}"
  prompt_into WPA_HOTSPOT_PRIORITY "Hotspot priority" "${WPA_HOTSPOT_PRIORITY}"
fi

# More Wi-Fi networks — pipe-separated list (do not use | in SSID).
if [[ "${CLEAR_EXTRA_WIFI}" -eq 1 ]]; then
  : > "${WIFI_EXTRA_LIST}"
fi
while true; do
  read -r -p "Add another Wi-Fi network? [y/N]: " add_wifi </dev/tty
  [[ "${add_wifi,,}" == "y" ]] || break
  extra_ssid="" extra_psk="" extra_prio="5"
  prompt_into extra_ssid "Extra Wi-Fi SSID" ""
  echo ""
  prompt_secret_into extra_psk "Extra Wi-Fi password" ""
  prompt_into extra_prio "Priority (higher = preferred when in range)" "5"
  extra_psk="$(sanitize_secret "${extra_psk}")"
  if [[ "${extra_ssid}" == *"|"* ]]; then
    echo "  SSID cannot contain | — skipped." >&2
    continue
  fi
  printf '%s|%s|%s\n' "${extra_ssid}" "${extra_psk}" "${extra_prio}" >> "${WIFI_EXTRA_LIST}"
  chmod 600 "${WIFI_EXTRA_LIST}"
  echo "  Added ${extra_ssid} to ${WIFI_EXTRA_LIST}"
done

echo ""
echo "--- LAN (press Enter to accept detected values) ---"
prompt_into ETH_USB "USB Ethernet iface (empty = none)" "${ETH_USB:-}"
prompt_into WIFI "Wi-Fi iface" "${WIFI}"
prompt_into GW "Gateway IP" "${DEF_GW}"
prompt_into VMBR_IP "Proxmox management IP/CIDR" "${DEF_VMBR}"

WPA_HOME_PSK="$(sanitize_secret "${WPA_HOME_PSK}")"
WPA_HOTSPOT_PSK="$(sanitize_secret "${WPA_HOTSPOT_PSK}")"
assert_valid_wifi_secrets "${OUT}" || exit 1

write_env "${OUT}" \
  ETH_USB "${ETH_USB}" \
  WIFI "${WIFI}" \
  GW "${GW}" \
  VMBR_IP "${VMBR_IP}" \
  WPA_COUNTRY "${WPA_COUNTRY}" \
  WPA_HOME_SSID "${WPA_HOME_SSID}" \
  WPA_HOME_PSK "${WPA_HOME_PSK}" \
  WPA_HOME_PRIORITY "${WPA_HOME_PRIORITY}" \
  WPA_HOTSPOT_SSID "${WPA_HOTSPOT_SSID}" \
  WPA_HOTSPOT_PSK "${WPA_HOTSPOT_PSK}" \
  WPA_HOTSPOT_PRIORITY "${WPA_HOTSPOT_PRIORITY}"

echo ""
echo "Saved: ${OUT}"
ls -la "${OUT}"
grep -E '^(GW|VMBR_IP|WIFI|ETH_USB|WPA_HOME_SSID)=' "${OUT}"
echo "(Password line hidden — check with: grep '^WPA_HOME_PSK=' ${OUT})"
if [[ -s "${WIFI_EXTRA_LIST}" ]]; then
  echo "Extra Wi-Fi networks: ${WIFI_EXTRA_LIST}"
fi
if [[ -z "${ETH_USB}" ]]; then
  echo ""
  echo "USB Ethernet not set (Wi-Fi-only for now). After plugging in USB:"
  echo "  bash ${SCRIPT_DIR}/enable-usb-ethernet.sh"
fi
echo ""
echo "Next:"
echo "  cd ${SCRIPT_DIR}"
echo "  bash setup-proxmox-network.sh --apply"
