# The Proxmox provider configuration mirrors the proxmox-connection module
# (infra/modules/proxmox-connection). The module validates inputs; this
# generated block passes them to the provider. Connection variables are
# declared in each stack's variables.tf and set via TF_VAR_ env vars in CI.
#
# Schema source: infra/connection-schema.yaml
# Generated by: scripts/generate-connection-adapters.sh (for variables.tf)

generate_hcl "providers.tf" {
  content {
    provider "proxmox" {
      endpoint  = var.proxmox_endpoint
      api_token = var.proxmox_api_token
      insecure  = var.proxmox_insecure_tls
    }
  }
}
