#!/bin/bash
# r2-defaults.sh — AUTO-GENERATED by scripts/generate-r2-config.sh from
# infra/r2-config.yaml. Do not edit manually.
# Contains non-secret defaults only.

R2_DEFAULT_BUCKET_NAME="autolab-opentofu-state"
R2_DEFAULT_REGION="auto"
R2_DEFAULT_TOKEN_NAME="autolab-opentofu-state"
