#!/bin/bash
# generate-packer-template-adapters.sh — Generate Packer template CI adapters
# from infra/packer/template-schema.yaml.
#
# Generates:
#   1. .github/actions/configure-packer-template/action.yml
#
# Usage:
#   bash scripts/generate-packer-template-adapters.sh
#   bash scripts/generate-packer-template-adapters.sh --check
#
# Requires: yq (https://github.com/mikefarah/yq)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA="${REPO_ROOT}/infra/packer/template-schema.yaml"
CHECK_MODE=0
LIB_ONLY="${AUTOLAB_GENERATOR_LIB_ONLY:-0}"

while [[ "$LIB_ONLY" -ne 1 && $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_MODE=1; shift ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if command -v yq &>/dev/null; then
  YQ="yq"
else
  echo "ERROR: yq is required. Install it: https://github.com/mikefarah/yq" >&2
  exit 1
fi

field_count() {
  "$YQ" '.fields | length' "$SCHEMA"
}

schema_field() {
  local index="$1"
  local key="$2"
  "$YQ" ".fields[$index]$key" "$SCHEMA"
}

schema_field_default() {
  local index="$1"
  local key="$2"
  local default="$3"
  "$YQ" ".fields[$index]$key // \"${default}\"" "$SCHEMA"
}

schema_name_to_env_suffix() {
  printf '%s' "$1" | tr '[:lower:]' '[:upper:]'
}

check_or_write() {
  local out="$1" tmp="$2"
  if [[ "$CHECK_MODE" -eq 1 ]]; then
    if ! diff -q "$tmp" "$out" &>/dev/null; then
      echo "DRIFT: $out differs from generated output" >&2
      rm "$tmp"
      return 1
    fi
    rm "$tmp"
    echo "OK: $out matches schema"
    return 0
  fi

  mv "$tmp" "$out"
  echo "Generated: $out"
}

generate_ci_action() {
  local out="${REPO_ROOT}/.github/actions/configure-packer-template/action.yml"
  local tmp
  tmp="$(mktemp)"
  mkdir -p "$(dirname "$out")"

  cat > "$tmp" << 'HEADER'
name: Configure Packer Template
description: >
  Write Packer template-specific environment variables.
  AUTO-GENERATED by scripts/generate-packer-template-adapters.sh from
  infra/packer/template-schema.yaml. Do not edit manually.

inputs:
HEADER

  local count
  count="$(field_count)"

  for ((i=0; i<count; i++)); do
    local name desc required
    name="$(schema_field "$i" '.name')"
    desc="$(schema_field "$i" '.description')"
    required="$(schema_field_default "$i" '.required_in_ci' "false")"

    echo "  ${name}:" >> "$tmp"
    echo "    description: ${desc}" >> "$tmp"
    echo "    required: ${required}" >> "$tmp"
    if [[ "$required" != "true" ]]; then
      echo "    default: ''" >> "$tmp"
    fi
  done

  cat >> "$tmp" << 'RUN_HEADER'

runs:
  using: composite
  steps:
    - name: Configure Packer template variables
      shell: bash
      env:
RUN_HEADER

  for ((i=0; i<count; i++)); do
    local name env_name
    name="$(schema_field "$i" '.name')"
    env_name="AUTOLAB_INPUT_$(schema_name_to_env_suffix "$name")"
    echo "        ${env_name}: \${{ inputs.${name} }}" >> "$tmp"
  done

  cat >> "$tmp" << 'RUN_START'
      run: |
        source "${GITHUB_WORKSPACE:-${PWD}}/scripts/lib/github-env.sh"

        csv_to_packer_string_list() {
          local raw="$1"
          local result="["
          local first=1
          local item
          local old_ifs="$IFS"
          IFS=','
          for item in $raw; do
            item="${item#"${item%%[![:space:]]*}"}"
            item="${item%"${item##*[![:space:]]}"}"
            if [[ -z "$item" ]]; then
              continue
            fi
            item="${item//\\/\\\\}"
            item="${item//\"/\\\"}"
            if [[ "$first" -eq 0 ]]; then
              result+=", "
            fi
            result+="\"${item}\""
            first=0
          done
          IFS="$old_ifs"
          result+="]"
          printf '%s' "$result"
        }

RUN_START

  for ((i=0; i<count; i++)); do
    local name packer_var field_type env_name
    name="$(schema_field "$i" '.name')"
    packer_var="$(schema_field "$i" '.packer_var')"
    field_type="$(schema_field "$i" '.type')"
    env_name="AUTOLAB_INPUT_$(schema_name_to_env_suffix "$name")"

    echo "        if [[ -n \"\$${env_name}\" ]]; then" >> "$tmp"
    if [[ "$field_type" == "list_string" ]]; then
      echo "          append_github_env \"PKR_VAR_${packer_var}\" \"\$(csv_to_packer_string_list \"\$${env_name}\")\"" >> "$tmp"
    else
      echo "          append_github_env \"PKR_VAR_${packer_var}\" \"\$${env_name}\"" >> "$tmp"
    fi
    echo "        fi" >> "$tmp"
    echo "" >> "$tmp"
  done

  check_or_write "$out" "$tmp"
}

if [[ "$LIB_ONLY" -eq 1 ]]; then
  return 0 2>/dev/null || exit 0
fi

generate_ci_action
echo ""
echo "Packer template adapters generated successfully."
