#!/bin/bash
# generate-network-env-adapters.sh — Generate network env adapters from the YAML schema.
#
# Reads docs/proxmox/config/network-env-schema.yaml and generates:
#   - docs/proxmox/config/network.env.example (template)
#   - docs/proxmox/scripts/lib/network-env-schema.sh (validation arrays)
#
# Usage:
#   bash scripts/generate-network-env-adapters.sh          # generate all adapters
#   bash scripts/generate-network-env-adapters.sh --check   # check for drift (CI)
#
# Requires: yq (https://github.com/mikefarah/yq)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA="${REPO_ROOT}/docs/proxmox/config/network-env-schema.yaml"
CHECK_MODE=0
LIB_ONLY="${AUTOLAB_GENERATOR_LIB_ONLY:-0}"

while [[ "$LIB_ONLY" -ne 1 && $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_MODE=1; shift ;;
    -h|--help) sed -n '2,11p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq is required. Install it: https://github.com/mikefarah/yq" >&2
  exit 1
fi

# --- Helper ---
field_count() {
  yq '.fields | length' "$SCHEMA"
}

schema_field() {
  local index="$1"
  local key="$2"
  yq ".fields[$index]$key" "$SCHEMA"
}

assert_supported_field_type() {
  case "$1" in
    string|number) ;;
    *) echo "ERROR: unsupported network env schema type '$1'" >&2; return 1 ;;
  esac
}

assert_supported_validation() {
  local validation="$1"
  case "$validation" in
    ""|null|"no newlines") ;;
    ^*) ;;
    *) echo "ERROR: unsupported network env validation '$validation'" >&2; return 1 ;;
  esac
}

# --- Generate network.env.example ---

generate_env_example() {
  local out="${REPO_ROOT}/docs/proxmox/config/network.env.example"
  local tmp
  tmp="$(mktemp)"

  {
    echo "# ============================================================================="
    echo "# Prefer the interactive helper (on the host as root):"
    echo "#   bash /root/proxmox-setup/scripts/configure-proxmox-network-env.sh"
    echo "# Or copy this file to /etc/default/proxmox-network.env and edit by hand."
    echo "# Then:  bash /root/proxmox-setup/scripts/setup-proxmox-network.sh --apply"
    echo "# ============================================================================="
    echo "#"
    echo "# AUTO-GENERATED by scripts/generate-network-env-adapters.sh from"
    echo "# docs/proxmox/config/network-env-schema.yaml. Do not edit manually."
    echo "#"

    local count
    count="$(field_count)"

    for ((i=0; i<count; i++)); do
      local name required default description sensitive
      name="$(schema_field "$i" '.name')"
      required="$(schema_field "$i" '.required')"
      default="$(schema_field "$i" '.default // ""')"
      description="$(schema_field "$i" '.description')"
      sensitive="$(schema_field "$i" '.sensitive // false')"
      assert_supported_field_type "$(schema_field "$i" '.type')"

      echo ""
      echo "# ${description}"

      if [[ "$sensitive" == "true" ]]; then
        echo "# SENSITIVE — use single quotes to avoid shell expansion"
        echo "# No newlines in the value."
        if [[ -z "$default" ]] || [[ "$default" == "null" ]]; then
          echo "${name}=''"
        else
          echo "${name}='${default}'"
        fi
      else
        if [[ -z "$default" ]] || [[ "$default" == "null" ]]; then
          echo "${name}="
        else
          echo "${name}=${default}"
        fi
      fi
    done
  } > "$tmp"

  if [[ "$CHECK_MODE" -eq 1 ]]; then
    if ! diff -q "$tmp" "$out" &>/dev/null; then
      echo "DRIFT: $out differs from generated output" >&2
      rm "$tmp"
      return 1
    fi
    rm "$tmp"
    echo "OK: $out matches schema"
    return 0
  fi

  mv "$tmp" "$out"
  echo "Generated: $out"
}

# --- Generate network-env-schema.sh ---

generate_schema_sh() {
  local out="${REPO_ROOT}/docs/proxmox/scripts/lib/network-env-schema.sh"
  local tmp
  tmp="$(mktemp)"

  local count
  count="$(field_count)"

  {
    echo "#!/bin/bash"
    echo "# Network environment schema — AUTO-GENERATED from network-env-schema.yaml"
    echo "# by scripts/generate-network-env-adapters.sh. Do not edit manually."
    echo "#"
    echo "# Provides: NETWORK_ENV_ALL_KEYS, NETWORK_ENV_REQUIRED_KEYS,"
    echo "#           NETWORK_ENV_OPTIONAL_KEYS, NETWORK_ENV_DEFAULTS,"
    echo "#           apply_network_env_defaults, secret_has_newline, sanitize_secret,"
    echo "#           assert_valid_wifi_secrets, validate_env, validate_field_value,"
    echo "#           describe_field"
    echo ""
    echo "# The env file is /etc/default/proxmox-network.env (or a path passed to"
    echo "# scripts via --config). It is sourced as shell, so values must be shell-safe."
    echo "#"
    echo "# Required keys must be present and non-empty."
    echo "# Optional keys have defaults listed in NETWORK_ENV_DEFAULTS."
    echo ""

    # ── All keys ──
    echo "# All schema keys in declaration order."
    echo "NETWORK_ENV_ALL_KEYS=("
    for ((i=0; i<count; i++)); do
      local name
      name="$(schema_field "$i" '.name')"
      echo "  ${name}"
    done
    echo ")"

    echo ""

    # ── Required keys ──
    echo "# Keys that MUST be present and non-empty."
    echo "NETWORK_ENV_REQUIRED_KEYS=("
    for ((i=0; i<count; i++)); do
      local name required
      name="$(schema_field "$i" '.name')"
      required="$(schema_field "$i" '.required')"
      if [[ "$required" == "true" ]]; then
        echo "  ${name}"
      fi
    done
    echo ")"

    echo ""

    # ── Optional keys ──
    echo "# Keys that MAY be absent; defaults are applied by setup scripts."
    echo "NETWORK_ENV_OPTIONAL_KEYS=("
    for ((i=0; i<count; i++)); do
      local name required
      name="$(schema_field "$i" '.name')"
      required="$(schema_field "$i" '.required')"
      if [[ "$required" != "true" ]]; then
        echo "  ${name}"
      fi
    done
    echo ")"

    echo ""

    # ── Defaults ──
    echo "# Default values for optional keys (key=default pairs)."
    echo "NETWORK_ENV_DEFAULTS=("
    for ((i=0; i<count; i++)); do
      local name required default
      name="$(schema_field "$i" '.name')"
      required="$(schema_field "$i" '.required')"
      default="$(schema_field "$i" '.default // ""')"
      if [[ "$required" != "true" ]] && [[ -n "$default" ]] && [[ "$default" != "null" ]]; then
        echo "  \"${name}=${default}\""
      fi
    done
    echo ")"

    echo ""
    cat << 'DEFAULTS_EOF'
# Apply generated defaults to unset or empty optional keys.
apply_network_env_defaults() {
  local kv key default
  for kv in "${NETWORK_ENV_DEFAULTS[@]}"; do
    key="${kv%%=*}"
    default="${kv#*=}"
    if [[ -z "${!key:-}" ]]; then
      printf -v "${key}" '%s' "${default}"
      export "${key}"
    fi
  done
}

DEFAULTS_EOF

    echo "# ── Validation ───────────────────────────────────────────────────────────────"
    echo ""

    cat << 'HELPERS_EOF'
# Return true when a value contains line breaks that would break env sourcing or WPA auth.
secret_has_newline() {
  local s="$1"
  [[ "${s}" == *$'\n'* || "${s}" == *$'\r'* ]]
}

# Print sanitized value to stdout; return 1 if anything was stripped.
sanitize_secret() {
  local s="$1"
  local clean="${s}"
  clean="${clean//$'\r'/}"
  clean="${clean//$'\n'/}"
  printf '%s' "${clean}"
  [[ "${s}" == "${clean}" ]]
}

HELPERS_EOF

    # Build field lists grouped by validation rule
    newline_fields=()
    number_fields=()
    regex_fields=()
    for ((i=0; i<count; i++)); do
      name="$(schema_field "$i" '.name')"
      validation="$(schema_field "$i" '.validation // ""')"
      ftype="$(schema_field "$i" '.type')"
      assert_supported_field_type "$ftype"
      assert_supported_validation "$validation"

      if [[ "$validation" == "no newlines" ]]; then
        newline_fields+=("${name}")
      fi
      if [[ "$validation" == ^* ]]; then
        regex_fields+=("${name}=${validation}")
      fi
      if [[ "$ftype" == "number" ]]; then
        number_fields+=("${name}")
      fi
    done

    # ── validate_field_value function ──
    echo "# Validate a single field's value against its schema constraints."
    echo "# Returns 0 on success, 1 on failure with error message on stderr."
    echo "# Usage: validate_field_value FIELD_NAME VALUE"
    echo "validate_field_value() {"
    echo "  local key=\"\$1\""
    echo "  local value=\"\$2\""
    echo "  case \"\${key}\" in"

    if [[ ${#newline_fields[@]} -gt 0 ]]; then
      local nl_pattern
      nl_pattern=$(IFS='|'; echo "${newline_fields[*]}")
      printf "    %s)\n" "${nl_pattern}"
      echo "      if secret_has_newline \"\${value}\"; then"
      echo "        echo \"ERROR: \${key} must not contain newlines\" >&2"
      echo "        return 1"
      echo "      fi"
      echo "      ;;"
    fi

    if [[ ${#number_fields[@]} -gt 0 ]]; then
      local num_pattern
      num_pattern=$(IFS='|'; echo "${number_fields[*]}")
      printf "    %s)\n" "${num_pattern}"
      echo "      if [[ -n \"\${value}\" ]] && ! [[ \"\${value}\" =~ ^[0-9]+$ ]]; then"
      echo "        echo \"ERROR: \${key} must be a number, got: \${value}\" >&2"
      echo "        return 1"
      echo "      fi"
      echo "      ;;"
    fi

    if [[ ${#regex_fields[@]} -gt 0 ]]; then
      local pair regex_name regex_value
      for pair in "${regex_fields[@]}"; do
        regex_name="${pair%%=*}"
        regex_value="${pair#*=}"
        printf "    %s)\n" "${regex_name}"
        printf "      if [[ -n \"\${value}\" ]] && ! [[ \"\${value}\" =~ %s ]]; then\n" "${regex_value}"
        echo "        echo \"ERROR: \${key} does not match required pattern\" >&2"
        echo "        return 1"
        echo "      fi"
        echo "      ;;"
      done
    fi

    echo "  esac"
    echo "  return 0"
    echo "}"

    echo ""
    echo "# Validate all schema-declared sensitive no-newline fields."
    echo "assert_valid_wifi_secrets() {"
    echo "  local config=\"\${1:-/etc/default/proxmox-network.env}\""
    echo "  local key value"
    for ((i=0; i<count; i++)); do
      local secret_name secret_validation
      secret_name="$(schema_field "$i" '.name')"
      secret_validation="$(schema_field "$i" '.validation // ""')"
      if [[ "$secret_validation" == "no newlines" ]]; then
        echo "  key=\"${secret_name}\""
        echo "  value=\"\${!key:-}\""
        echo "  if [[ -n \"\${value}\" ]] && secret_has_newline \"\${value}\"; then"
        echo "    echo \"ERROR: \${key} in \${config} contains a newline (often shows as \\\$'\\\\n…' in the file).\" >&2"
        echo "    echo \"  Fix: re-run configure-proxmox-network-env.sh, or edit \${config} and use single quotes.\" >&2"
        echo "    return 1"
        echo "  fi"
      fi
    done
    echo "  return 0"
    echo "}"

    echo ""
    echo "# ── validate_env function ──"
    echo ""
    cat << 'VALIDATE_EOF'
# Validate that all required keys are present and non-empty, and that all
# set values pass field-level validation (type checks, no-newlines, etc.).
# Returns 0 on success, 1 on failure with error messages on stderr.
#
# Usage:
#   source "${CONFIG}"
#   validate_env || die "Invalid env"
validate_env() {
  local config="${1:-/etc/default/proxmox-network.env}"
  local missing=0
  local key

  for key in "${NETWORK_ENV_REQUIRED_KEYS[@]}"; do
    if [[ -z "${!key:-}" ]]; then
      echo "ERROR: Required key ${key} is missing or empty in ${config}" >&2
      missing=$((missing + 1))
    else
      validate_field_value "${key}" "${!key}" || missing=$((missing + 1))
    fi
  done

  for key in "${NETWORK_ENV_OPTIONAL_KEYS[@]}"; do
    if [[ -n "${!key:-}" ]]; then
      validate_field_value "${key}" "${!key}" || missing=$((missing + 1))
    fi
  done

  if [[ "${missing}" -gt 0 ]]; then
    echo "ERROR: ${missing} validation error(s) in ${config}" >&2
    return 1
  fi
  return 0
}
VALIDATE_EOF

    echo ""
    echo "# ── Key description ──────────────────────────────────────────────────────────"
    echo ""

    # ── describe_field function ──
    echo "# Print a one-line description of a key (including type)."
    echo "# Useful for help text and error messages."
    echo "describe_field() {"
    echo "  local key=\"\$1\""
    echo "  case \"\${key}\" in"
    for ((i=0; i<count; i++)); do
      local name description ftype
      name="$(schema_field "$i" '.name')"
      description="$(schema_field "$i" '.description')"
      ftype="$(schema_field "$i" '.type')"
      # Pad the key + ) for nice alignment (match original formatting)
      printf "    %-24s echo \"%s [type: %s]\" ;;\n" "${name})" "${description}" "${ftype}"
    done
    echo "    *) echo \"Unknown key: \${key}\" ;;"
    echo "  esac"
    echo "}"
  } > "$tmp"

  if [[ "$CHECK_MODE" -eq 1 ]]; then
    if ! diff -q "$tmp" "$out" &>/dev/null; then
      echo "DRIFT: $out differs from generated output" >&2
      rm "$tmp"
      return 1
    fi
    rm "$tmp"
    echo "OK: $out matches schema"
    return 0
  fi

  mv "$tmp" "$out"
  chmod 755 "$out"
  echo "Generated: $out"
}

# --- Main ---

if [[ "$LIB_ONLY" -eq 1 ]]; then
  return 0 2>/dev/null || exit 0
fi

errors=0

if ! generate_env_example; then
  errors=$((errors + 1))
fi

if ! generate_schema_sh; then
  errors=$((errors + 1))
fi

if [[ "$errors" -gt 0 ]]; then
  exit 1
fi

echo ""
echo "All adapters generated successfully."
echo "Run 'bash scripts/generate-network-env-adapters.sh --check' in CI to detect drift."
