#!/bin/bash
# generate-r2-config.sh — Generate Terramate R2 globals and shell defaults from infra/r2-config.yaml.
#
# Usage:
#   bash scripts/generate-r2-config.sh                       # generate both artifacts
#   bash scripts/generate-r2-config.sh --check                # check for drift (both)
#   bash scripts/generate-r2-config.sh --terramate            # generate only terramate globals
#   bash scripts/generate-r2-config.sh --defaults             # generate only shell defaults
#   bash scripts/generate-r2-config.sh --terramate --check    # check only terramate globals
#   bash scripts/generate-r2-config.sh --defaults --check     # check only shell defaults

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="${REPO_ROOT}/infra/r2-config.yaml"
OUT_TERRAMATE="${REPO_ROOT}/infra/terramate.tm.hcl"
OUT_DEFAULTS="${REPO_ROOT}/scripts/lib/r2-defaults.sh"
CHECK_MODE=0
GENERATE_TERRAMATE=1
GENERATE_DEFAULTS=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)      CHECK_MODE=1; shift ;;
    --terramate)  GENERATE_TERRAMATE=1; GENERATE_DEFAULTS=0; shift ;;
    --defaults)   GENERATE_TERRAMATE=0; GENERATE_DEFAULTS=1; shift ;;
    -h|--help)    sed -n '2,9p' "$0"; exit 0 ;;
    *)            echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq is required. Install it: https://github.com/mikefarah/yq" >&2
  exit 1
fi

bucket="$(yq -r '.bucket' "$CONFIG")"
region="$(yq -r '.region' "$CONFIG")"
token_name="$(yq -r '.token_name' "$CONFIG")"

errors=0

# ── Generate Terramate globals ─────────────────────────────────
if [[ "$GENERATE_TERRAMATE" -eq 1 ]]; then
  tmp_terramate="$(mktemp)"
  cat > "$tmp_terramate" << EOF
# Global config — AUTO-GENERATED by scripts/generate-r2-config.sh from
# infra/r2-config.yaml. Do not edit manually.
# Reference these in generated HCL via: global.r2_bucket, global.r2_region, etc.

globals {
  # Cloudflare R2 state backend
  r2_bucket = "${bucket}"
  r2_region = "${region}"
}
EOF

  if [[ "$CHECK_MODE" -eq 1 ]]; then
    if diff -q "$tmp_terramate" "$OUT_TERRAMATE" &>/dev/null; then
      echo "OK: $OUT_TERRAMATE matches source"
      rm "$tmp_terramate"
    else
      echo "DRIFT: $OUT_TERRAMATE differs from generated output" >&2
      rm "$tmp_terramate"
      errors=$((errors + 1))
    fi
  else
    mv "$tmp_terramate" "$OUT_TERRAMATE"
    echo "Generated: $OUT_TERRAMATE"
  fi
fi

# ── Generate shell defaults ────────────────────────────────────
if [[ "$GENERATE_DEFAULTS" -eq 1 ]]; then
  tmp_defaults="$(mktemp)"
  cat > "$tmp_defaults" << EOF
#!/bin/bash
# r2-defaults.sh — AUTO-GENERATED by scripts/generate-r2-config.sh from
# infra/r2-config.yaml. Do not edit manually.
# Contains non-secret defaults only.

R2_DEFAULT_BUCKET_NAME="${bucket}"
R2_DEFAULT_REGION="${region}"
R2_DEFAULT_TOKEN_NAME="${token_name}"
EOF

  if [[ "$CHECK_MODE" -eq 1 ]]; then
    if diff -q "$tmp_defaults" "$OUT_DEFAULTS" &>/dev/null; then
      echo "OK: $OUT_DEFAULTS matches source"
      rm "$tmp_defaults"
    else
      echo "DRIFT: $OUT_DEFAULTS differs from generated output" >&2
      rm "$tmp_defaults"
      errors=$((errors + 1))
    fi
  else
    mv "$tmp_defaults" "$OUT_DEFAULTS"
    echo "Generated: $OUT_DEFAULTS"
  fi
fi

if [[ "$errors" -gt 0 ]]; then
  exit 1
fi
