#!/bin/bash
# generate-connection-adapters.sh — Generate OpenTofu, Packer, and CI adapter
# files from the connection schema in infra/connection-schema.yaml.
#
# Generates:
#   1. infra/modules/proxmox-connection/variables.tf  (OpenTofu module vars)
#   2. infra/packer/connection-vars.pkr.hcl            (Packer connection vars, generated)
#   3. infra/_base/connection-variables.tm.hcl         (Terramate code-gen for stack vars)
#   4. .github/actions/configure-proxmox-connection/action.yml (CI env adapter)
#
# Usage:
#   bash scripts/generate-connection-adapters.sh          # generate all adapters
#   bash scripts/generate-connection-adapters.sh --check   # check for drift (CI)
#   bash scripts/generate-connection-adapters.sh --opentofu # generate only OpenTofu
#   bash scripts/generate-connection-adapters.sh --packer    # generate only Packer
#   bash scripts/generate-connection-adapters.sh --stack     # generate only stack vars
#   bash scripts/generate-connection-adapters.sh --ci        # generate only CI adapter
#
# Requires: yq (https://github.com/mikefarah/yq)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA="${REPO_ROOT}/infra/connection-schema.yaml"
CHECK_MODE=0
GENERATE_OPENTOFU=1
GENERATE_PACKER=1
GENERATE_STACK=1
GENERATE_CI=1

LIB_ONLY="${AUTOLAB_GENERATOR_LIB_ONLY:-0}"

# Parse arguments
while [[ "$LIB_ONLY" -ne 1 && $# -gt 0 ]]; do
  case "$1" in
    --check)      CHECK_MODE=1; shift ;;
    --opentofu)   GENERATE_OPENTOFU=1; GENERATE_PACKER=0; GENERATE_STACK=0; GENERATE_CI=0; shift ;;
    --packer)     GENERATE_OPENTOFU=0; GENERATE_PACKER=1; GENERATE_STACK=0; GENERATE_CI=0; shift ;;
    --stack)      GENERATE_OPENTOFU=0; GENERATE_PACKER=0; GENERATE_STACK=1; GENERATE_CI=0; shift ;;
    --ci)         GENERATE_OPENTOFU=0; GENERATE_PACKER=0; GENERATE_STACK=0; GENERATE_CI=1; shift ;;
    -h|--help)    sed -n '2,12p' "$0"; exit 0 ;;
    *)            echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Check for yq
if command -v yq &>/dev/null; then
  YQ="yq"
else
  echo "ERROR: yq is required. Install it: https://github.com/mikefarah/yq" >&2
  echo "  brew install yq  # macOS" >&2
  echo "  snap install yq  # Linux" >&2
  exit 1
fi

# --- Helper functions ---

# Read a field from the schema
schema_field() {
  local index="$1"
  local key="$2"
  "$YQ" ".fields[$index]$key" "$SCHEMA"
}

schema_field_default() {
  local index="$1"
  local key="$2"
  local default="$3"
  "$YQ" ".fields[$index]$key // \"${default}\"" "$SCHEMA"
}

schema_type_to_hcl() {
  case "$1" in
    string) echo "string" ;;
    bool)   echo "bool" ;;
    number) echo "number" ;;
    *)      echo "ERROR: unsupported schema type '$1'" >&2; return 1 ;;
  esac
}

schema_name_to_env_suffix() {
  printf '%s' "$1" | tr '[:lower:]' '[:upper:]'
}

emit_hcl_validation() {
  local tmp="$1" var_name="$2" validation="$3" error_msg="$4" indent="$5"
  if [[ -n "$validation" ]] && [[ "$validation" != "null" ]]; then
    echo "${indent}validation {" >> "$tmp"
    echo "${indent}  condition     = can(regex(\"${validation}\", var.${var_name}))" >> "$tmp"
    echo "${indent}  error_message = \"${error_msg}\"" >> "$tmp"
    echo "${indent}}" >> "$tmp"
  fi
}

# Count fields in the schema
field_count() {
  "$YQ" '.fields | length' "$SCHEMA"
}

# Check a generated file for drift against the expected content.
# Args: $1 = description, $2 = path, $3 = temp file with new content
check_or_write() {
  local desc="$1" out="$2" tmp="$3"
  if [[ "$CHECK_MODE" -eq 1 ]]; then
    if ! diff -q "$tmp" "$out" &>/dev/null; then
      echo "DRIFT: $out differs from generated output" >&2
      rm "$tmp"
      return 1
    fi
    rm "$tmp"
    echo "OK: $out matches schema"
    return 0
  fi
  mv "$tmp" "$out"
  echo "Generated: $out"
}

# --- Generate OpenTofu variables.tf (proxmox-connection module) ---

generate_opentofu() {
  local out="${REPO_ROOT}/infra/modules/proxmox-connection/variables.tf"
  local tmp
  tmp="$(mktemp)"

  cat > "$tmp" << 'HEADER'
# ---------------------------------------------------------------------------
# proxmox-connection — centralized Proxmox connection configuration
#
# AUTO-GENERATED by scripts/generate-connection-adapters.sh from
# infra/connection-schema.yaml. Do not edit manually.
#
# This module owns the Proxmox connection schema with validation.
# It does NOT create any resources — it validates and normalises inputs so
# that every stack and adapter (OpenTofu provider, Packer source) shares a
# single definition of "how we connect to Proxmox".
#
# OpenTofu provider blocks cannot reference module outputs, so the provider
# still reads from var.proxmox_* directly.  This module exists to:
#   1. Validate connection parameters at plan time
#   2. Provide a single source of truth for node_name and derived values
#   3. Let compute modules consume connection config through one module call
# ---------------------------------------------------------------------------

HEADER

  local count
  count="$(field_count)"

  for ((i=0; i<count; i++)); do
    local name desc type validation sensitive default module_var error_msg
    name="$(schema_field "$i" '.name')"
    desc="$(schema_field "$i" '.description')"
    type="$(schema_field "$i" '.type')"
    validation="$(schema_field "$i" '.validation')"
    sensitive="$(schema_field "$i" '.sensitive')"
    default="$(schema_field "$i" '.default')"
    module_var="$(schema_field "$i" '.module_var')"
    error_msg="$(schema_field_default "$i" '.error_message' "Validation failed for ${module_var}.")"

    local hcl_type
    hcl_type="$(schema_type_to_hcl "$type")"

    echo "" >> "$tmp"
    echo "variable \"${module_var}\" {" >> "$tmp"
    echo "  description = \"${desc}\"" >> "$tmp"
    echo "  type        = ${hcl_type}" >> "$tmp"

    if [[ "$default" != "null" ]] && [[ -n "$default" ]]; then
      echo "  default     = ${default}" >> "$tmp"
    fi

    if [[ "$sensitive" == "true" ]]; then
      echo "  sensitive   = true" >> "$tmp"
    fi

    if [[ -n "$validation" ]] && [[ "$validation" != "null" ]]; then
      emit_hcl_validation "$tmp" "$module_var" "$validation" "$error_msg" "  "
    fi

    echo "}" >> "$tmp"
  done

  check_or_write "OpenTofu module variables" "$out" "$tmp"
}

# --- Generate Packer connection variables (connection fields only) ---

generate_packer() {
  local out="${REPO_ROOT}/infra/packer/connection-vars.pkr.hcl"
  local tmp
  tmp="$(mktemp)"

  cat > "$tmp" << 'HEADER'
# ---------------------------------------------------------------------------
# Packer connection variables — AUTO-GENERATED from infra/connection-schema.yaml
# by scripts/generate-connection-adapters.sh. Do not edit manually.
#
# Template-specific variables are in template-vars.pkr.hcl (hand-maintained).
# ---------------------------------------------------------------------------

HEADER

  local count
  count="$(field_count)"

  for ((i=0; i<count; i++)); do
    local name desc type sensitive default packer_var
    name="$(schema_field "$i" '.name')"
    desc="$(schema_field "$i" '.description')"
    type="$(schema_field "$i" '.type')"
    sensitive="$(schema_field "$i" '.sensitive')"
    default="$(schema_field "$i" '.default')"
    packer_var="$(schema_field "$i" '.packer_var')"

    local pkr_type
    pkr_type="$(schema_type_to_hcl "$type")"

    echo "" >> "$tmp"
    echo "variable \"${packer_var}\" {" >> "$tmp"
    echo "  type        = ${pkr_type}" >> "$tmp"
    echo "  description = \"${desc}\"" >> "$tmp"

    if [[ "$sensitive" == "true" ]]; then
      echo "  sensitive   = true" >> "$tmp"
    fi

    # Only set default for optional fields
    if [[ "$default" != "null" ]] && [[ -n "$default" ]]; then
      echo "  default     = ${default}" >> "$tmp"
    fi

    echo "}" >> "$tmp"
  done

  check_or_write "Packer connection variables" "$out" "$tmp"
}

# --- Generate Terramate code-gen for stack connection variables ---

generate_stack() {
  local out="${REPO_ROOT}/infra/_base/connection-variables.tm.hcl"
  local tmp
  tmp="$(mktemp)"

  cat > "$tmp" << 'HEADER'
// ---------------------------------------------------------------------------
// Stack connection variables — AUTO-GENERATED from infra/connection-schema.yaml
// by scripts/generate-connection-adapters.sh. Do not edit manually.
//
// This Terramate code-gen block produces a _connection-variables.tf file in
// every stack, declaring the Proxmox connection variables that the provider
// block and the proxmox-connection module both need.
//
// The provider block cannot reference module outputs (a Terraform/OpenTofu
// limitation), so connection variables must be declared at the stack level.
// This generated file ensures they stay in sync with the connection schema.
// ---------------------------------------------------------------------------

HEADER

  # Generate the Terramate generate_hcl block
  cat >> "$tmp" << 'TMHCL_START'
generate_hcl "_connection-variables.tf" {
  content {
TMHCL_START

  local count
  count="$(field_count)"

  for ((i=0; i<count; i++)); do
    local name desc type validation sensitive default opentofu_var ci_env error_msg
    name="$(schema_field "$i" '.name')"
    desc="$(schema_field "$i" '.description')"
    type="$(schema_field "$i" '.type')"
    validation="$(schema_field "$i" '.validation')"
    sensitive="$(schema_field "$i" '.sensitive')"
    default="$(schema_field "$i" '.default')"
    opentofu_var="$(schema_field "$i" '.opentofu_var')"
    ci_env="$(schema_field "$i" '.ci_env')"
    error_msg="$(schema_field_default "$i" '.error_message' "Validation failed for ${opentofu_var}.")"

    local hcl_type
    hcl_type="$(schema_type_to_hcl "$type")"

    # Stack variables use the proxmox_* naming (matching CI TF_VAR_ convention)
    echo "" >> "$tmp"
    echo "    variable \"${opentofu_var}\" {" >> "$tmp"
    echo "      description = \"${desc}\"" >> "$tmp"
    echo "      type        = ${hcl_type}" >> "$tmp"

    if [[ "$sensitive" == "true" ]]; then
      echo "      sensitive   = true" >> "$tmp"
    fi

    # Only set default for optional fields
    if [[ "$default" != "null" ]] && [[ -n "$default" ]]; then
      echo "      default     = ${default}" >> "$tmp"
    fi

    if [[ -n "$validation" ]] && [[ "$validation" != "null" ]]; then
      emit_hcl_validation "$tmp" "$opentofu_var" "$validation" "$error_msg" "      "
    fi

    echo "    }" >> "$tmp"
  done

  echo "  }" >> "$tmp"
  echo "}" >> "$tmp"

  check_or_write "Stack connection variables" "$out" "$tmp"
}

# --- Generate GitHub composite action for CI env vars ---

generate_ci() {
  local out="${REPO_ROOT}/.github/actions/configure-proxmox-connection/action.yml"
  local tmp
  tmp="$(mktemp)"

  cat > "$tmp" << 'HEADER'
name: Configure Proxmox Connection
description: >
  Write Proxmox connection environment variables for OpenTofu and/or Packer.
  AUTO-GENERATED by scripts/generate-connection-adapters.sh from
  infra/connection-schema.yaml. Do not edit manually.

inputs:
HEADER

  local count
  count="$(field_count)"

  for ((i=0; i<count; i++)); do
    local name desc default
    name="$(schema_field "$i" '.name')"
    desc="$(schema_field "$i" '.description')"
    default="$(schema_field "$i" '.default')"

    echo "  ${name}:" >> "$tmp"
    echo "    description: ${desc}" >> "$tmp"
    if [[ "$default" != "null" ]] && [[ -n "$default" ]]; then
      echo "    required: false" >> "$tmp"
      echo "    default: '${default}'" >> "$tmp"
    else
      echo "    required: true" >> "$tmp"
    fi
  done

  cat >> "$tmp" << 'STATIC_INPUTS'
  emit_tf_vars:
    description: Write TF_VAR_ environment variables
    required: false
    default: 'true'
  emit_packer_vars:
    description: Write PKR_VAR_ environment variables
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Configure Proxmox connection variables
      shell: bash
      env:
STATIC_INPUTS

  for ((i=0; i<count; i++)); do
    local name env_name
    name="$(schema_field "$i" '.name')"
    env_name="AUTOLAB_INPUT_$(schema_name_to_env_suffix "$name")"
    echo "        ${env_name}: \${{ inputs.${name} }}" >> "$tmp"
  done

  cat >> "$tmp" << 'RUN_START'
      run: |
        source "${GITHUB_WORKSPACE:-${PWD}}/scripts/lib/github-env.sh"

        if [[ '${{ inputs.emit_tf_vars }}' == 'true' ]]; then
RUN_START

  for ((i=0; i<count; i++)); do
    local name opentofu_var env_name
    name="$(schema_field "$i" '.name')"
    opentofu_var="$(schema_field "$i" '.opentofu_var')"
    env_name="AUTOLAB_INPUT_$(schema_name_to_env_suffix "$name")"
    echo "          append_github_env \"TF_VAR_${opentofu_var}\" \"\$${env_name}\"" >> "$tmp"
  done

  cat >> "$tmp" << 'PACKER_START'
        fi

        if [[ '${{ inputs.emit_packer_vars }}' == 'true' ]]; then
PACKER_START

  for ((i=0; i<count; i++)); do
    local name packer_var env_name
    name="$(schema_field "$i" '.name')"
    packer_var="$(schema_field "$i" '.packer_var')"
    env_name="AUTOLAB_INPUT_$(schema_name_to_env_suffix "$name")"
    echo "          append_github_env \"PKR_VAR_${packer_var}\" \"\$${env_name}\"" >> "$tmp"
  done

  cat >> "$tmp" << 'FOOTER'
        fi
FOOTER

  check_or_write "CI connection action" "$out" "$tmp"
}

# --- Main ---

if [[ "$LIB_ONLY" -eq 1 ]]; then
  return 0 2>/dev/null || exit 0
fi

errors=0

if [[ "$GENERATE_OPENTOFU" -eq 1 ]]; then
  if ! generate_opentofu; then
    errors=$((errors + 1))
  fi
fi

if [[ "$GENERATE_PACKER" -eq 1 ]]; then
  if ! generate_packer; then
    errors=$((errors + 1))
  fi
fi

if [[ "$GENERATE_STACK" -eq 1 ]]; then
  if ! generate_stack; then
    errors=$((errors + 1))
  fi
fi

if [[ "$GENERATE_CI" -eq 1 ]]; then
  if ! generate_ci; then
    errors=$((errors + 1))
  fi
fi

if [[ "$errors" -gt 0 ]]; then
  exit 1
fi

echo ""
echo "All adapters generated successfully."
echo "Run 'bash scripts/generate-connection-adapters.sh --check' in CI to detect drift."
