# ---------------------------------------------------------------------------
# proxmox-connection — centralized Proxmox connection configuration
#
# AUTO-GENERATED by scripts/generate-connection-adapters.sh from
# infra/connection-schema.yaml. Do not edit manually.
#
# This module owns the Proxmox connection schema with validation.
# It does NOT create any resources — it validates and normalises inputs so
# that every stack and adapter (OpenTofu provider, Packer source) shares a
# single definition of "how we connect to Proxmox".
#
# OpenTofu provider blocks cannot reference module outputs, so the provider
# still reads from var.proxmox_* directly.  This module exists to:
#   1. Validate connection parameters at plan time
#   2. Provide a single source of truth for node_name and derived values
#   3. Let compute modules consume connection config through one module call
# ---------------------------------------------------------------------------


variable "endpoint" {
  description = "Proxmox API endpoint URL (must be HTTPS)"
  type        = string
  validation {
    condition     = can(regex("^https://", var.endpoint))
    error_message = "Proxmox endpoint must be an HTTPS URL."
  }
}

variable "api_token" {
  description = "Proxmox API token in USER@REALM!TOKENID=TOKEN_SECRET format"
  type        = string
  sensitive   = true
  validation {
    condition     = can(regex("^[^@]+@[^!]+!.+=.+$", var.api_token))
    error_message = "Proxmox API token must be in USER@REALM!TOKENID=TOKEN_SECRET format."
  }
}

variable "node_name" {
  description = "Proxmox node name shown in the UI"
  type        = string
  validation {
    condition     = can(regex("^[a-zA-Z0-9][a-zA-Z0-9-]*$", var.node_name))
    error_message = "Node name must start with an alphanumeric character and contain only alphanumeric characters and hyphens."
  }
}

variable "insecure_tls" {
  description = "Allow self-signed Proxmox TLS certificates"
  type        = bool
  default     = true
}
