---
- name: Install Docker when enabled for this machine
  ansible.builtin.apt:
    name: docker.io
    state: present
  when: autolab_docker_enabled | bool

- name: Enable Docker when enabled for this machine
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: autolab_docker_enabled | bool
